### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by konewuser** [timtraversy/new_version#12]
Lets say my local version is 2.0.0 but app store version is 1.0.0. Now, the logic of this package returns that the app can still be updated, so it is quite important to always confirm that the version number is smaller than the app store version.

Another feature is to provide a way to customize the text of the dialog.

Thank you so much and really appreciate if you could make such changes.

**Comment by eric-taix** [comment]
Not sure that it's possible to downgrade a version on stores!

**Comment by timtraversy** [comment]
Hey, thanks for the issue. But agreeing with @eric-taix, I don't think the package needs to be able to check if its larger than the version in the store, since store versions can't be downgraded.

On your second note, those features have been added to the package in the last release.

Closing this, let me know if you have any other Qs.
