### ISSUE TITLE
No alert

### ISSUE THREAD

**Issue by daljitjhajj** [timtraversy/new_version#33]
I used this plug-in in my app.. But app not showing alert if play store version is installed..... And when I tried it with debug mode.. It shows alert, but in that case play store shows only Open option instead of Update..
Sorry for my bad communication skills

**Comment by timtraversy** [comment]
Here's my understanding of your question:
- If you instal the store version you don't see an upgrade alert. This is the expected behavior, because your are using the most recent version from the store.
- When you open a locally built debug version you see the alert, but you still have the most recent version of the app on your phone, so the Play Store just prompts you to open it.

I don't see any unexpected behavior here, let me know if I'm missing something.

**Comment by timtraversy** [comment]
I can re-open this if you have more information.
