### ISSUE TITLE
Can't fetch version status

### ISSUE THREAD

**Issue by noobmonxter** [timtraversy/new_version#47]
The argument type 'VersionStatus?' can't be assigned to the parameter type 'VersionStatus'

This is my code 
```
final versionStatus = await newversion.getVersionStatus();
newversion.showUpdateDialog(context: context, versionStatus: versionStatus);
```

**Comment by timtraversy** [comment]
Ah yes, I should update the example code for projects using more recent Dart versions.

Dart >= 2.12.0 now includes null safety, which you can read about [here](https://dart.dev/null-safety).

`getVersionStatus` returns a `VersionStatus?`, which is possibly null because it is annotated with a question mark. So before you use it, you have to check if it's null.

```
if (versionStatus != null) {
    newversion.showUpdateDialog(context: context, versionStatus: versionStatus);
}
```

**Comment by timtraversy** [comment]
Just updated example code.

**Comment by timtraversy** [comment]
I'm going to close this now that the example code is correct.
